travis:
  secure:
    BINSTAR_TOKEN: hkQ9JnN+rwTriT2Xft7THbHdFqvMc5rWtMttFsa7NxjW0vAfD47ZJ3J3xkGmwkGoVY4nTQ0vrTrvdkhiuBNVLghR7GB6YTtLujX8AyrBYUdANKpV9AOMtpNkI3Pf90+UIe+wSfdFuuESBxKFzMIjB3Zq/JjB2mVHR8/baNvMYI8KLMNhWf0EUfWAmJlHWd4Dhlxa8c7JyziwXuRoQ70p7ESFWNqfegAO/gyW/VpCDkRBaAoMcy8vNysxVlyOrkz7tpYhIc3YmbmYiWrZvDAtROT/dKXLVxUCcwzTXf6qbQXTLrfAndtZnb1EItSKvWyn5ufbFGCDGATpsCU6wUIhoKLe/wyS8n2i2nwxpV6QgwEs2KJibhmiwoGP4mY5oBLFacpbgLIYAESwHMJ3Gna7Qi9D/Vix22mKIPZYWX0s2s3K7lWi5myKHqwhar7z8at9BnnhelIfFVXXIsriuQM5T8p6hv6Q5Xlpcf15VDzRiVEXWDH5iKmQsLvV8m9KEjfW8FIfC2onF0NBqSM+FNihIVbehQYAjqarSJMhfJzUXYIOMaROQkii3ao166iwhbgal6XPpuGXj57Z8IlbDLzhiZlKXrVcMv1CPb9TJFQVKSSordWjLYzqEKemJbt3pyjqvZd0uLQ6q+PGX5cypk7aYBBXHgP6qYq9Q0vHg90ZJX4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
